# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "ipy/v5.0.0"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[pip]"
    labels:
      - "dependencies"
      - "pip"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "[github-actions]"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
